#!/bin/bash
#
#               __                             
#              /\ \__                          
#   __    _____\ \ ,_\ _____     __      ___   
# /'__`\ /\ '__`\ \ \//\ '__`\ /'__`\   /'___\ 
#/\ \L\.\\ \ \L\ \ \ \\ \ \L\ /\ \L\.\_/\ \__/ 
#\ \__/.\_\ \ ,__/\ \__\ \ ,__\ \__/.\_\ \____\
# \/__/\/_/\ \ \/  \/__/\ \ \/ \/__/\/_/\/____/
#           \ \_\        \ \_\                 
#            \/_/         \/_/    
# a pacman wrapper with syntax based on debian's apt
# (c) arcetera 2015 - wtfpl

SYNTAX="$1"
INPUT="$2"

_usage() {
	cat <<- EOF
    $(basename $0): a pacman wrapper with apt syntax

    no argument/invalid argument - print this help
    install    - installs a package
    search     - searches for a package in the repos
    remove     - removes a package
    upgrade    - upgrades the system fully, refreshing repos and upgrading packages
    update     - only refreshes the repos (bad practice, do not run this without running 'upgrade' immediately after
    download   - only download a package into pacman's cache without installing it
    autoremove - remove dependencies that are no longer needed
                 (usually should not be needed as 'remove' should remove dependencies along with the package)
    show       - shows information about the package
    clean      - clears pacman's cache
    autoclean  - clears pacman's cache (same as clean)
    policy     - prints mirrorlist
    list       - lists all installed packages
    listmore   - lists all installed packages with all info
    listless   - lists how many packages are installed
    build      - builds package from PKGBUILD
	EOF
}

case "$SYNTAX" in
	install)
		sudo pacman -S $INPUT
		;;
	search)
		pacman -Ss $INPUT
		;;
	remove)
		sudo pacman -Rs $INPUT
		;;
	upgrade)
		sudo pacman -Syu
		;;
	update)
		sudo pacman -Sy
		echo 'run aptpac upgrade *immediately*.'
		echo 'pacman does not support partial upgrades.'
		echo 'running merely 'upgrade' would suffice.'
		echo 'failure to do so could result in a broken installation.'
		;;
	download)
		sudo pacman -Sw $INPUT
		;;
	autoremove)
		sudo pacman -Qdtq | pacman -Rs -
		;;
	show)
		pacman -Qi $INPUT
		;;
	clean)
		sudo pacman -Sc
		;;
	autoclean)
		sudo pacman -Sc
		;;
	policy)
		less /etc/pacman.d/mirrorlist
		;;
	list)
		pacman -Q
		;;
	listmore)
		pacman -Qi
		;;
	listless)
		pacman -Q | wc -l
		;;
	build)
                makepkg -sri
		;;
		*)
		_usage && exit 1
		;;
esac

exit 0
